'use strict';
const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs/promises'); const os = require('node:os'); const path = require('node:path'); const { execFile } = require('node:child_process'); const { promisify } = require('node:util'); const execFileAsync = promisify(execFile);
const { workspaceRevision, assertGitRepository } = require('../src/orchestrator/revision'); const { captureWorkspaceChangeState, buildTaskChangeManifest } = require('../src/orchestrator/task-change-manifest'); const { createBatchViewTool } = require('../src/copilot/batch-view-tool'); const { resolveRunCommandCwd } = require('../src/copilot/run-command-tool');
async function repo(dir, file, text) { await fs.mkdir(dir, { recursive: true }); await execFileAsync('git', ['init', '-q', dir]); await execFileAsync('git', ['-C', dir, 'config', 'user.email', 'test@example.com']); await execFileAsync('git', ['-C', dir, 'config', 'user.name', 'Test']); await fs.writeFile(path.join(dir, file), text); await execFileAsync('git', ['-C', dir, 'add', '.']); await execFileAsync('git', ['-C', dir, 'commit', '-qm', 'init']); }
async function fixture(t) { const base = await fs.mkdtemp(path.join(os.tmpdir(), 'convergent-multi-')); t.after(() => fs.rm(base, { recursive: true, force: true })); const a = path.join(base, 'repo-a'); const b = path.join(base, 'repo-b'); await repo(a, 'a.txt', 'alpha\n'); await repo(b, 'b.txt', 'beta\n'); return { a, b, roots: [{ name: 'repo-a', path: a }, { name: 'repo-b', path: b }] }; }
test('combined revision changes when either repo changes', async (t) => { const f = await fixture(t); await assertGitRepository(f.a, f.roots); const before = await workspaceRevision(f.a, f.roots); await fs.writeFile(path.join(f.b, 'b.txt'), 'beta changed\n'); assert.notEqual(await workspaceRevision(f.a, f.roots), before); });
test('change manifest qualifies non-primary paths', async (t) => { const f = await fixture(t); const baseline = await captureWorkspaceChangeState(f.a, null, f.roots); await fs.writeFile(path.join(f.b, 'b.txt'), 'beta changed\n'); const current = await captureWorkspaceChangeState(f.a, baseline.head, f.roots, baseline.heads); const manifest = buildTaskChangeManifest(baseline, current); assert.equal(manifest.count, 1); assert.equal(manifest.entries[0].path, 'repo-b::b.txt'); });
test('batch_view searches and reads non-primary root', async (t) => { const f = await fixture(t); let tool; createBatchViewTool((name, config) => (tool = { name, ...config }), f.a, f.roots); const result = await tool.handler({ queries: ['beta'], paths: ['repo-b::b.txt'] }); assert.ok(result.searches[0].matches.some((match) => match.workspaceFolder === 'repo-b')); assert.equal(result.files[0].path, 'repo-b::b.txt'); assert.match(result.files[0].content, /beta/); });
test('run_command selects workspace folder', async (t) => { const f = await fixture(t); const resolved = resolveRunCommandCwd(f.a, f.roots, '.', 'repo-b'); assert.equal(resolved.absolute, f.b); assert.equal(resolved.display, 'repo-b::.'); assert.throws(() => resolveRunCommandCwd(f.a, f.roots, '../repo-a', 'repo-b'), /stay inside workspace folder/); });
